var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(c,d,e){return c==a&&"q"==d&&e==b}}));return!0===b.q}catch(c){return!1}};
$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,f){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),k=Object.seal({}),m=new a([[h,2],[k,3]]);if(2!=m.get(h)||3!=m.get(k))return!1;m.delete(h);m.set(k,4);return!m.has(h)&&4==m.get(k)}catch(n){return!1}}function c(){}function d(h){var k=typeof h;return"object"===k&&null!==h||"function"===k}function e(h){if(!$jscomp.owns(h,g)){var k=new c;$jscomp.defineProperty(h,g,{value:k})}}function f(h){if(!$jscomp.ISOLATE_POLYFILLS){var k=Object[h];k&&(Object[h]=
function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return k(m)})}}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var p=0,l=function(h){this.id_=(p+=Math.random()+1).toString();if(h){h=$jscomp.makeIterator(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};l.prototype.set=function(h,k){if(!d(h))throw Error("Invalid WeakMap key");
e(h);if(!$jscomp.owns(h,g))throw Error("WeakMap key fail: "+h);h[g][this.id_]=k;return this};l.prototype.get=function(h){return d(h)&&$jscomp.owns(h,g)?h[g][this.id_]:void 0};l.prototype.has=function(h){return d(h)&&$jscomp.owns(h,g)&&$jscomp.owns(h[g],this.id_)};l.prototype.delete=function(h){return d(h)&&$jscomp.owns(h,g)&&$jscomp.owns(h[g],this.id_)?delete h[g][this.id_]:!1};return l},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var l=Object.seal({x:4}),h=new a($jscomp.makeIterator([[l,"s"]]));if("s"!=h.get(l)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var k=h.entries(),m=k.next();if(m.done||m.value[0]!=l||"s"!=m.value[1])return!1;m=k.next();return m.done||4!=m.value[0].x||"t"!=m.value[1]||!k.next().done?!1:!0}catch(n){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var c=new WeakMap,d=function(l){this.data_={};this.head_=g();this.size=0;if(l){l=$jscomp.makeIterator(l);for(var h;!(h=l.next()).done;)h=h.value,this.set(h[0],h[1])}};d.prototype.set=function(l,h){l=0===l?0:l;var k=e(this,l);k.list||(k.list=this.data_[k.id]=[]);k.entry?k.entry.value=h:(k.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:l,value:h},k.list.push(k.entry),
this.head_.previous.next=k.entry,this.head_.previous=k.entry,this.size++);return this};d.prototype.delete=function(l){l=e(this,l);return l.entry&&l.list?(l.list.splice(l.index,1),l.list.length||delete this.data_[l.id],l.entry.previous.next=l.entry.next,l.entry.next.previous=l.entry.previous,l.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=g();this.size=0};d.prototype.has=function(l){return!!e(this,l).entry};d.prototype.get=function(l){return(l=
e(this,l).entry)&&l.value};d.prototype.entries=function(){return f(this,function(l){return[l.key,l.value]})};d.prototype.keys=function(){return f(this,function(l){return l.key})};d.prototype.values=function(){return f(this,function(l){return l.value})};d.prototype.forEach=function(l,h){for(var k=this.entries(),m;!(m=k.next()).done;)m=m.value,l.call(h,m[1],m[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var e=function(l,h){var k=h&&typeof h;"object"==k||"function"==k?c.has(h)?k=c.get(h):
(k=""+ ++p,c.set(h,k)):k="p_"+h;var m=l.data_[k];if(m&&$jscomp.owns(l.data_,k))for(l=0;l<m.length;l++){var n=m[l];if(h!==h&&n.key!==n.key||h===n.key)return{id:k,list:m,index:l,entry:n}}return{id:k,list:m,index:-1,entry:void 0}},f=function(l,h){var k=l.head_;return $jscomp.iteratorPrototype(function(){if(k){for(;k.head!=l.head_;)k=k.previous;for(;k.next!=k.head;)return k=k.next,{done:!1,value:h(k)};k=null}return{done:!0,value:void 0}})},g=function(){var l={};return l.previous=l.next=l.head=l},p=0;
return d},"es6","es3");
$jscomp.polyfill("Set",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),e=new a($jscomp.makeIterator([d]));if(!e.has(d)||1!=e.size||e.add(d)!=e||1!=e.size||e.add({x:4})!=e||2!=e.size)return!1;var f=e.entries(),g=f.next();if(g.done||g.value[0]!=d||g.value[1]!=d)return!1;g=f.next();return g.done||g.value[0]==d||4!=g.value[0].x||g.value[1]!=g.value[0]?!1:f.next().done}catch(p){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var c=function(d){this.map_=new Map;if(d){d=$jscomp.makeIterator(d);for(var e;!(e=d.next()).done;)this.add(e.value)}this.size=this.map_.size};c.prototype.add=function(d){d=0===d?0:d;this.map_.set(d,d);this.size=this.map_.size;return this};c.prototype.delete=function(d){d=this.map_.delete(d);this.size=this.map_.size;return d};c.prototype.clear=function(){this.map_.clear();this.size=0};c.prototype.has=
function(d){return this.map_.has(d)};c.prototype.entries=function(){return this.map_.entries()};c.prototype.values=function(){return this.map_.values()};c.prototype.keys=c.prototype.values;c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(d,e){var f=this;this.map_.forEach(function(g){return d.call(e,g,g,f)})};return c},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(p){return p};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}},"es6","es3");
var C={STATE:{SELECT_RULES:0,EDIT_RULESET:1},SELECTION_MODE:{ACTIVE:0,NOT_ACTIVE:1},BUTTON_TEXT:{ADD_TO_RULESET:"Add to Custom Ruleset",REMOVE_FROM_RULESET:"Remove from Custom Ruleset",SELECT:"Select",UNSELECT:"Unselect"}},state,selectionMode=C.SELECTION_MODE.NOT_ACTIVE,shouldHideAddedRules=!1,rulesWithCopiesInRuleset=new Set,categoriesToRulesInRuleset=new Map,nameIndexes=new Map,currentSelection=new Set,categoryTemplateString='<div class="category" id="" data-name=""><div class="categoryHead"><h2><input class="editableCategoryName" type="text" placeholder="UNNAMED CATEGORY" value="" autocomplete="off"/></h2><button class="button" id="categorySelectAll">Select Category</button><button class="button" id="categoryUnselectAll" style="display:none;">Clear Selection</button></div><div class="categoryContent"></div></div>',
categoryTemplate=document.createElement("div");categoryTemplate.innerHTML=categoryTemplateString;categoryTemplate=categoryTemplate.firstElementChild;
var allDefaultCategories=Array.from(document.querySelectorAll('div.category[data-name=""]')),allRulesInDefaultCategories=Array.from(document.querySelectorAll('div.category[data-name=""] div.rule')),selectRulesStateTitle=document.querySelector("div#titleHeader h1#selectRulesStateTitle"),editRulesetStateTitle=document.querySelector("div#titleHeader h1#editRulesetStateTitle"),tocContainer=document.querySelector("div#toc ul"),categoriesContainer=document.getElementById("content"),filterResults=document.getElementById("filterResults"),
moveToCategoryButton=document.getElementById("moveToCategoryButton"),hideAddedRulesButton=document.getElementById("showAddedRules"),selectRulesStateButton=document.getElementById("selectRulesState"),editRulesetStateButton=document.getElementById("editRulesetState"),generateRulesetButton=document.getElementById("generateRulesetButton"),removeRulesButton=document.getElementById("removeAllFromCustomRuleset"),allUnselectAllButton=document.getElementById("allUnselectAll"),scrollToTop=document.getElementById("scrollToTop"),
filterInput=document.getElementById("filterInput"),confidential=document.getElementById("confidential"),modalOptions=new Set;modalOptions.add("modalExistingCategories");modalOptions.add("modalNewCategoryName");
var modal=document.getElementById("modal"),addToDefaultCategoriesOption=document.getElementById("addToDefaultCategories"),addToExistingCategoryOption=document.getElementById("radioModalExistingCategories"),addToNewCategoryOption=document.getElementById("radioModalNewCategory"),displayCurrentSelectionElement=document.getElementById("currentSelectionElement"),newCategoryNameInput=document.getElementById("modalNewCategoryName");
function notify(a){a||(a="Internal error!");window.vscodeOpen?vscode.postMessage({type:"NOTIFICATION",data:{eventType:"ALERT",context:{message:a}}}):alert(a)}function scrollFunction(){scrollToTop.style.display=800<document.body.scrollTop||800<document.documentElement.scrollTop?"block":"none"}function scrollToTopFunction(){document.body.scrollTop?document.body.scrollTop=0:document.documentElement.scrollTop&&(document.documentElement.scrollTop=0)}
function adjustTextareaHeight(a){a.style.height="";a.style.height=a.scrollHeight+3+"px";a.dataset.adjusted="true"}function updateFilterResults(a,b){nOfChecks=a?nOfChecks+b:nOfChecks-b;""===filterInputValue?filterResults.textContent=nOfChecks+" checks":(nOfChecksMatched=a?nOfChecksMatched+b:nOfChecksMatched-b,filterResults.textContent=nOfChecksMatched+"/"+nOfChecks+" checks matched")}
function changeTableColor(a,b){var c=a.querySelectorAll("th");a=a.querySelectorAll("td");var d="";b&&(d="added");c.forEach(function(e){e.className=d});a.forEach(function(e){e.className=d})}function disableOtherModalOptions(a){if("noid"!==a){var b=document.getElementById(a);b&&(b.disabled=!1)}modalOptions.forEach(function(c){c!==a&&(c=document.getElementById(c))&&(c.disabled=!0)})}
function changeStates(){scrollToTopFunction();state===C.STATE.SELECT_RULES&&null===nOfAllChecks&&filterSearch();var a=state===C.STATE.SELECT_RULES?"":"none",b=state===C.STATE.SELECT_RULES?"none":"";state===C.STATE.SELECT_RULES&&shouldHideAddedRules?allDefaultCategories.forEach(function(d){var e=d.querySelectorAll("div.rule");e=$jscomp.makeIterator(e);for(var f=e.next();!f.done;f=e.next())if(!rulesWithCopiesInRuleset.has(f.value)){d.style.display=a;document.querySelector("li[data-id='"+d.id+"']").style.display=
a;break}}):allDefaultCategories.forEach(function(d){d.style.display=a;document.querySelector("li[data-id='"+d.id+"']").style.display=a});var c=0;categoriesToRulesInRuleset.forEach(function(d,e){c+=d.size;e.style.display=b;document.querySelector("li[data-id='"+e.id+"']").style.display=b;state===C.STATE.EDIT_RULESET&&d.forEach(function(f){f=f.querySelector("textarea");f.dataset.adjusted&&"false"!==f.dataset.adjusted||adjustTextareaHeight(f)})});nOfChecks=state===C.STATE.SELECT_RULES?shouldHideAddedRules?
nOfAllChecks-rulesWithCopiesInRuleset.size:nOfAllChecks:c;filterResults.textContent=nOfChecks+" checks"}
function editRulesetState(){selectionMode===C.SELECTION_MODE.ACTIVE&&clearCurrentSelection();""!==filterInputValue&&(filterInput.value="",parseInput(),filterSearch());state=C.STATE.EDIT_RULESET;moveToCategoryButton.textContent="Move to Category";addToDefaultCategoriesOption.style.display="none";hideAddedRulesButton.style.display="none";selectRulesStateTitle.style.display="none";editRulesetStateTitle.style.display="";confidential.style.display="none";selectRulesStateButton.className="button";editRulesetStateButton.className=
"clickedButton";null!==rulesWithCopiesInRuleset&&0!==rulesWithCopiesInRuleset.size&&(generateRulesetButton.style.display="");changeStates()}
function selectRulesState(){selectionMode===C.SELECTION_MODE.ACTIVE&&clearCurrentSelection();""!==filterInputValue&&(filterInput.value="",parseInput(),filterSearch());state=C.STATE.SELECT_RULES;moveToCategoryButton.textContent="Add to Category";addToDefaultCategoriesOption.style.display="";hideAddedRulesButton.style.display="";selectRulesStateTitle.style.display="";editRulesetStateTitle.style.display="none";confidential.style.display="inline";selectRulesStateButton.className="clickedButton";editRulesetStateButton.className=
"button";generateRulesetButton.style.display="none";changeStates()}function checkIfCategoryShouldBeHidden(a,b){var c=a.querySelector("div.categoryContent").children,d=!0;for(j=0;j<c.length;j++)if("none"!==c[j].style.display){d=!1;break}d&&(a.style.display="none",b.style.display="none")}function checkIfCategoriesShouldBeHidden(){allDefaultCategories.forEach(function(a){var b=document.querySelector('li[data-id="'+a.id+'"]');checkIfCategoryShouldBeHidden(a,b)})}
function hideRule(a,b,c){a.style.display="none";document.querySelector('li[data-id="'+a.id+'"]').style.display="none";c&&(a=document.querySelector('li[data-id="'+b.id+'"]'),checkIfCategoryShouldBeHidden(b,a))}function showRule(a,b){a.style.display="";document.querySelector('li[data-id="'+a.id+'"]').style.display="";"none"===b.style.display&&(b.style.display="",document.querySelector('li[data-id="'+b.id+'"]').style.display="")}
function hideAddedRules(a){var b=0;a?(hideAddedRulesButton.className="clickedButton",shouldHideAddedRules=!0,rulesWithCopiesInRuleset.forEach(function(c){var d=c.closest("div.category");hideRule(c,d,!1);b++}),""===filterInputValue&&checkIfCategoriesShouldBeHidden()):(shouldHideAddedRules=!1,hideAddedRulesButton.className="button",rulesWithCopiesInRuleset.forEach(function(c){var d=c.closest("div.category");showRule(c,d);b++}));""===filterInputValue?updateFilterResults(!a,b):filterSearch()}
function createEditableRuleCopy(a){var b=a.cloneNode(!0);b.querySelector("button#duplicateRule").style.visibility="visible";b.querySelector("table").style.cursor="";changeIdForRule(b,!1);a=b.querySelector("tr#nameData");a.lastElementChild.style.display="";a.removeChild(a.firstElementChild.nextElementSibling);a=b.querySelector("tr#titleData");a.lastElementChild.style.display="";a.removeChild(a.firstElementChild.nextElementSibling);a=b.querySelector("tr#severityData");a.lastElementChild.style.display=
"";a.removeChild(a.firstElementChild.nextElementSibling);a=b.querySelector("tr#descriptionData");a.lastElementChild.style.display="";a.removeChild(a.firstElementChild.nextElementSibling);if(a=b.querySelector("tr#parametersDescriptionData"))a.firstElementChild.textContent="Parameters Description",b.querySelector("tr#parametersValuesData").style.display="";if(a=b.querySelector("tr#autocorrectEnabledData"))a.style.display="",a.querySelectorAll("td input").forEach(function(c){return c.name=b.id});if(a=
b.querySelector("tr#autocorrectParametersDescriptionData"))a.firstElementChild.textContent="Autocorrect Parameters Description",b.querySelector("tr#autocorrectParametersValuesData").style.display="";return b}function createRuleTocCopy(a,b,c){a=document.querySelector("li[data-id='"+a.id+"']").cloneNode(!0);a.dataset.id=b.id;var d=a.querySelector("a");d.href="#"+b.id;c&&(b=b.querySelector("tr#nameData td input").value,d.textContent=b);return a}
function addToCategoriesInRuleset(a,b){var c=categoriesToRulesInRuleset.get(b);c?c.add(a):(c=new Set,c.add(a),categoriesToRulesInRuleset.set(b,c))}function removeFromCategoriesInRuleset(a,b){var c=categoriesToRulesInRuleset.get(b);if(c&&1===c.size)return categoriesToRulesInRuleset.delete(b),!0;if(c&&1!==c.size)return c.delete(a),!1}
function removeRuleSectionFromCategory(a,b,c){var d=document.querySelector('li[data-id="'+b.id+'"]');removeFromCategoriesInRuleset(a,b)?(categoriesContainer.removeChild(b),tocContainer.removeChild(d)):c||(b.querySelector("div.categoryContent").removeChild(a),c=d.querySelector("ul"),a=document.querySelector('li[data-id="'+a.id+'"]'),c.removeChild(a),""!==filterInputValue&&checkIfCategoryShouldBeHidden(b,d))}
function addRuleSectionToCategory(a,b,c,d,e){addToCategoriesInRuleset(a,c);var f=c.querySelector("div.categoryContent");c=document.querySelector('li[data-id="'+c.id+'"] ul');d&&e?(f.insertBefore(a,d),c.insertBefore(b,e)):(f.appendChild(a),c.appendChild(b))}
function createAndAddRuleCopy(a,b,c,d,e,f){if(!rulesWithCopiesInRuleset.has(a)){c.textContent=C.BUTTON_TEXT.REMOVE_FROM_RULESET;c.className="clickedButton";c.style.visibility="visible";c=createEditableRuleCopy(a);var g=createRuleTocCopy(a,c,!1);addRuleSectionToCategory(c,g,f,null,null);rulesWithCopiesInRuleset.add(a);d.style.display="none";changeTableColor(b,!0);""!==filterInputValue&&unhighlightRule(c.getElementsByTagName("tr"),!0);shouldHideAddedRules&&(hideRule(a,e,!0),updateFilterResults(!1,1));
return c}}function markRuleInDefaultCategoryRemoved(a,b,c,d){c.textContent=C.BUTTON_TEXT.ADD_TO_RULESET;c.className="button";rulesWithCopiesInRuleset.delete(a);d.style.display="";changeTableColor(b,!1)}
function markRuleInDefaultCategoryAdded(a){var b=a.querySelector("button#addRuleButton");b.textContent=C.BUTTON_TEXT.REMOVE_FROM_RULESET;b.className="clickedButton";b.style.visibility="visible";rulesWithCopiesInRuleset.add(a);a.querySelector("button#selectRuleButton").style.display="none";changeTableColor(a.querySelector("table"),!0)}
function changeIdForRule(a,b,c){var d=nameIndexes.get(a.dataset.originalId);d=d?d+1:1;nameIndexes.set(a.dataset.originalId,d);a.id=a.dataset.originalId+"_"+d;b&&(a=a.querySelector("tr#nameData td input"),c=c.querySelector("tr#nameData td input").value,a.placeholder=c+"_"+d,a.value=c+"_"+d)}function getRulesetEditorCategory(a){var b=document.querySelector("div.category[data-name='"+a+"']");return b?b:createCategory(a,state===C.STATE.SELECT_RULES)}
function duplicateRule(a){var b=a.closest("div.category"),c=a.cloneNode(!0);changeIdForRule(c,!0,a);var d=createRuleTocCopy(a,c,!0),e=c.querySelector("tr#autocorrectEnabledData");e&&e.querySelectorAll("td input").forEach(function(f){return f.name=c.id});addRuleSectionToCategory(c,d,b,a.nextElementSibling,document.querySelector('li[data-id="'+a.id+'"]').nextElementSibling);updateFilterResults(!0,1)}
function addOrRemoveRule(a){var b=a.querySelector("button#addRuleButton"),c=a.querySelector("button#selectRuleButton"),d=b.textContent,e=a.querySelector("table"),f=a.closest("div.category");d===C.BUTTON_TEXT.ADD_TO_RULESET?createAndAddRuleCopy(a,e,b,c,f,getRulesetEditorCategory(f.id)):d===C.BUTTON_TEXT.REMOVE_FROM_RULESET&&(state===C.STATE.SELECT_RULES?(markRuleInDefaultCategoryRemoved(a,e,b,c),(b=Array.from(document.querySelectorAll('div.rule[data-original-id="'+a.id+'"]')))&&b.forEach(function(g){if(g!==
a){var p=g.closest("div.category");removeRuleSectionFromCategory(g,p,!1)}})):state===C.STATE.EDIT_RULESET&&(removeRuleSectionFromCategory(a,f,!1),updateFilterResults(!1,1),(b=document.querySelectorAll('div.rule[data-original-id="'+a.dataset.originalId+'"]'))&&1===b.length&&(b=document.querySelector('div.rule[id="'+a.dataset.originalId+'"]'))&&(markRuleInDefaultCategoryRemoved(b,b.querySelector("table"),b.querySelector("button#addRuleButton"),b.querySelector("button#selectRuleButton")),shouldHideAddedRules&&
(b.style.display="",document.querySelector('li[data-id="'+a.dataset.originalId+'"]').style.display="")),null===rulesWithCopiesInRuleset||0===rulesWithCopiesInRuleset.size)&&(generateRulesetButton.style.display="none"))}
function getCurrentCategoriesNames(){var a=document.createElement("select"),b=new Set;categoriesToRulesInRuleset.forEach(function(c,d){c=d.id;void 0!==d.dataset.name&&""!==d.dataset.name&&(c=d.dataset.name);b.has(c)||(b.add(c),d=document.createElement("option"),d.value=c,d.text=c,a.appendChild(d))});state===C.STATE.SELECT_RULES&&allDefaultCategories.forEach(function(c){var d=c.id;void 0!==c.dataset.name&&""!==c.dataset.name&&(d=c.dataset.name);b.has(d)||(b.add(d),c=document.createElement("option"),
c.value=d,c.text=d,a.appendChild(c))});a.firstElementChild.selected=!0;a.setAttribute("id","modalExistingCategories");return a}function setInfoForCategoryTemplate(a){var b=categoryTemplate.cloneNode(!0),c=nameIndexes.get(a);c=c?c+1:1;nameIndexes.set(a,c);b.id=a+"_"+c;b.dataset.name=a;b.querySelector("div.categoryHead").firstElementChild.lastElementChild.value=a;return b}
function createCategory(a,b){var c=setInfoForCategoryTemplate(a),d=document.createElement("li");d.dataset.id=c.id;var e=document.createElement("a");e.href="#"+c.id;e.textContent=a;a=document.createElement("ul");d.appendChild(e);d.appendChild(a);b&&(c.style.display="none",d.style.display="none");tocContainer.prepend(d);categoriesContainer.prepend(c);return c}
function displayMoveToCategoryModal(){if(0===currentSelection.size)notify("No selected rules!");else{var a=modal.querySelector("div.modal-content"),b=a.querySelector("div#moveToExistingCategories"),c=getCurrentCategoriesNames();c.addEventListener("onclick",function(e){b.firstElementChild.click()});b.appendChild(c);a.querySelector("h2").textContent=moveToCategoryButton.textContent;var d=document.createElement("ul");currentSelection.forEach(function(e){var f=document.createElement("li");e=state===C.STATE.SELECT_RULES?
e.querySelector("tr#nameData td").textContent:e.querySelector("tr#nameData td input").value;e=document.createTextNode(e);f.appendChild(e);d.appendChild(f)});displayCurrentSelectionElement.appendChild(d);newCategoryNameInput.value="";modal.style.display="block"}}function clickSelectButtonForRule(a,b){"none"===a.style.display||(state!==C.STATE.SELECT_RULES||rulesWithCopiesInRuleset.has(a))&&state!==C.STATE.EDIT_RULESET||(a=a.querySelector("button#selectRuleButton"),a.textContent===b&&a.click())}
function clearCurrentSelection(){currentSelection.forEach(function(a){a=a.querySelector("button#selectRuleButton");a.textContent===C.BUTTON_TEXT.UNSELECT&&a.click()})}function closeModal(a,b){b.removeChild(b.lastElementChild);displayCurrentSelectionElement.removeChild(displayCurrentSelectionElement.firstElementChild);addToExistingCategoryOption.click();modal.style.display="none";a&&clearCurrentSelection()}
function performModalAction(a){var b=addToExistingCategoryOption.parentNode;if(a){var c=addToExistingCategoryOption.checked?b.lastElementChild.value:addToNewCategoryOption.checked?""!==newCategoryNameInput.value?newCategoryNameInput.value:newCategoryNameInput.placeholder:null;var d;null!==c&&(d=getRulesetEditorCategory(c));var e=new Set;currentSelection.forEach(function(f){var g=f.closest("div.category");if(null===c||g.id!==d.id){var p=f;if(state===C.STATE.SELECT_RULES)null===c&&(d=getRulesetEditorCategory(g.id)),
p=createAndAddRuleCopy(f,f.querySelector("table"),f.querySelector("button#addRuleButton"),f.querySelector("button#selectRuleButton"),g,d),e.add(p);else{var l=document.querySelector('li[data-id="'+f.id+'"]');addRuleSectionToCategory(p,l,d,null,null);removeRuleSectionFromCategory(f,g,!0)}}});e.forEach(function(f){return currentSelection.add(f)})}closeModal(a,b)}
function setSelectionMode(a,b,c,d){selectionMode=a?C.SELECTION_MODE.ACTIVE:C.SELECTION_MODE.NOT_ACTIVE;moveToCategoryButton.style.display=b;allUnselectAllButton.style.display=b;state===C.STATE.SELECT_RULES?(allDefaultCategories.forEach(function(e){return e.querySelector("button#categoryUnselectAll").style.display=b}),allRulesInDefaultCategories.forEach(function(e){e.querySelector("button#addRuleButton").style.visibility=c;a&&rulesWithCopiesInRuleset.has(e)||(e.querySelector("table").style.cursor=
d)})):(generateRulesetButton.style.display=a?"none":"",removeRulesButton.style.display=b,categoriesToRulesInRuleset.forEach(function(e,f){f.querySelector("button#categoryUnselectAll").style.display=b;e.forEach(function(g){g.querySelector("button#addRuleButton").style.visibility=c;g.querySelector("button#duplicateRule").style.visibility=c;g.querySelector("table").style.cursor=d})}))}
function escapeXML(a){return a.replaceAll(/[\n<>&"']/g,function(b){switch(b){case "\n":return"&#10;";case "<":return"&lt;";case ">":return"&gt;";case "&":return"&amp;";case '"':return"&quot;";case "'":return"&apos;";default:return b}})}
function addParametersToRuleXML(a,b,c,d){a=$jscomp.makeIterator(a.children);for(var e=a.next();!e.done;e=a.next()){var f=e.value;e=f.firstElementChild.textContent.split(" ")[0];var g=f.lastElementChild;f=g.value;""===f&&(f=g.placeholder);g=d?b.createElement("autocorrect-input"):b.createElement("property");f=escapeXML(f);g.setAttribute("key",e);g.setAttribute("value",f);c.appendChild(g)}}
function download(a,b,c){window.vscodeOpen?vscode.postMessage({type:"NOTIFICATION",data:{eventType:"GENERATE",context:{content:a}}}):(a=new Blob([a],{type:c}),saveAs(a,b))}window.onclick=function(a){a.target===modal&&performModalAction(!1)};window.onscroll=function(){scrollFunction()};document.body.addEventListener("click",hideHelp);
categoriesContainer.addEventListener("click",function(a){if("BUTTON"===a.target.tagName){var b=a.target.closest("div.rule"),c=a.target.id;"duplicateRule"===c&&duplicateRule(b);"addRuleButton"===c&&addOrRemoveRule(b);"categorySelectAll"===c&&a.target.closest("div.category").querySelectorAll("div.rule").forEach(function(d){clickSelectButtonForRule(d,C.BUTTON_TEXT.SELECT)});"categoryUnselectAll"===c&&a.target.closest("div.category").querySelectorAll("div.rule").forEach(function(d){clickSelectButtonForRule(d,
C.BUTTON_TEXT.UNSELECT)});"selectRuleButton"===c&&(b=a.target.closest("div.rule"),c=b.querySelector("table"),a.target.textContent===C.BUTTON_TEXT.SELECT?(currentSelection.add(b),a.target.textContent=C.BUTTON_TEXT.UNSELECT,a.target.className="clickedButton",c.className="selected",selectionMode===C.SELECTION_MODE.NOT_ACTIVE&&setSelectionMode(!0,"","hidden","pointer")):(currentSelection.delete(b),a.target.textContent=C.BUTTON_TEXT.SELECT,a.target.className="button",c.className="",0===currentSelection.size&&
setSelectionMode(!1,"none","visible","")))}"INPUT"===a.target.tagName&&(a.target.select(),"editableCategoryName"===a.target.className&&0<a.target.value.length&&(a.target.size=a.target.value.length));selectionMode===C.SELECTION_MODE.ACTIVE&&(a=a.target.closest("table"))&&(a=a.closest("div.rule"),(state===C.STATE.SELECT_RULES&&!rulesWithCopiesInRuleset.has(a)||state===C.STATE.EDIT_RULESET)&&a.querySelector("button#selectRuleButton").click())});
categoriesContainer.addEventListener("input",function(a){if("INPUT"===a.target.tagName)if("editableCategoryName"===a.target.className){var b=a.target.closest("div.category"),c=document.querySelector('li[data-id="'+b.id+'"]'),d=a.target.value;""!==d?(c.firstElementChild.textContent=d,b.dataset.name=d):(c.firstElementChild.textContent="UNNAMED CATEGORY",b.dataset.name=d,d="UNNAMED CATEGORY");a.target.size=d.length}else"inputText"===a.target.className&&(b=a.target.closest("tr"),"nameData"===b.id?(b=
a.target.value,c=a.target.closest("div.rule").id,document.querySelector('li[data-id="'+c+'"]').firstElementChild.textContent=""!==b?b:a.target.placeholder):"titleData"===b.id&&(a.target.dataset.changed="true"));"TEXTAREA"===a.target.tagName&&(adjustTextareaHeight(a.target),a.target.dataset.changed="true")});editRulesetStateButton.addEventListener("click",function(){state===C.STATE.SELECT_RULES&&editRulesetState()});
selectRulesStateButton.addEventListener("click",function(){state===C.STATE.EDIT_RULESET&&selectRulesState()});removeRulesButton.addEventListener("click",function(){currentSelection.forEach(function(a){addOrRemoveRule(a)});setSelectionMode(!1,"none","visible","");generateRulesetButton.style.display="none";currentSelection.clear()});allUnselectAllButton.addEventListener("click",clearCurrentSelection);hideAddedRulesButton.addEventListener("click",function(){hideAddedRules(!shouldHideAddedRules)});
moveToCategoryButton.addEventListener("click",displayMoveToCategoryModal);document.getElementById("doneChoosingCategories").addEventListener("click",function(){performModalAction(!0)});document.getElementById("cancelChoosingCategories").addEventListener("click",function(){performModalAction(!1)});document.querySelector("span.close").addEventListener("click",function(){performModalAction(!1)});document.querySelector('label[for="radioModalDefaultCategories"]').addEventListener("click",function(){this.parentNode.firstElementChild.click()});
document.querySelector('label[for="modalExistingCategories"]').addEventListener("click",function(){this.parentNode.firstElementChild.click()});document.querySelector('label[for="modalNewCategoryName"]').addEventListener("click",function(){this.parentNode.firstElementChild.click()});addToNewCategoryOption.addEventListener("click",function(){disableOtherModalOptions("modalNewCategoryName")});document.getElementById("radioModalDefaultCategories").addEventListener("click",function(){disableOtherModalOptions("noid")});
addToExistingCategoryOption.addEventListener("click",function(){disableOtherModalOptions("modalExistingCategories")});document.querySelector("button.helpButton").addEventListener("click",toggleHelp);filterInput.addEventListener("keydown",function(a){"Enter"===a.key&&(parseInput(),filterSearch())});
document.getElementById("allSelectAll").addEventListener("click",function(){var a=C.BUTTON_TEXT.SELECT;state===C.STATE.SELECT_RULES?allRulesInDefaultCategories.forEach(function(b){clickSelectButtonForRule(b,a)}):categoriesToRulesInRuleset.forEach(function(b,c){b.forEach(function(d){clickSelectButtonForRule(d,a)})})});
generateRulesetButton.addEventListener("click",function(){var a=document.implementation.createDocument(null,null),b=a.createProcessingInstruction("xml",'version="1.0" encoding="UTF-8"');a.insertBefore(b,a.firstChild);var c=a.createElement("ruleset");c.setAttribute("version","2");b=editRulesetStateTitle.firstElementChild;b.value&&""!==b.value?c.setAttribute("name",b.value):c.setAttribute("name",b.placeholder);var d=new Map;try{categoriesToRulesInRuleset.forEach(function(g,p){var l=p.dataset.name;if(""===
p.dataset.name)throw Error("Internal error!");var h=a.createElement("category");h.setAttribute("name",l);g.forEach(function(k){var m=a.createElement("rule"),n=k.dataset.originalId;m.setAttribute("id",n);var u=k.querySelector("tr#nameData td input");u=""!==u.value?u.value:u.placeholder;if(d.has(u))throw m=d.get(u),Error("Name '"+u+"' is duplicated for rules with "+(n===m?"id: '"+n:"ids: '"+m+"', '"+n)+"'!");d.set(u,n);m.setAttribute("name",escapeXML(u));n=k.querySelector("tr#titleData td input");n.dataset.changed&&
"true"===n.dataset.changed&&n.value&&m.setAttribute("title",escapeXML(n.value));n=k.querySelector("tr#severityData td select");"ERROR"!==n.value&&m.setAttribute("severity",n.value);n=k.querySelector("tr#descriptionData td textarea");n.dataset.changed&&"true"===n.dataset.changed&&n.value&&""!==n.value&&m.setAttribute("description",escapeXML(n.value));(n=k.querySelector("tr#autocorrectEnabledData td"))&&n.firstElementChild.checked&&m.setAttribute("autocorrect","on");(n=k.querySelector("tr#parametersValuesData td"))&&
addParametersToRuleXML(n,a,m,!1);(k=k.querySelector("tr#autocorrectParametersValuesData td"))&&addParametersToRuleXML(k,a,m,!0);h.appendChild(m)});c.appendChild(h)})}catch(g){notify(g.message);return}a.appendChild(c);try{var e=(new XMLSerializer).serializeToString(a),f=(new XmlBeautify).beautify(e,{indent:"  ",useSelfClosingElement:!0});download(f,"verissimo_ruleset.xml","text/plain")}catch(g){notify("Internal Error.")}});var nOfAllChecks=null,nOfChecks,nOfChecksMatched,filterInputValue,inputMap;
function parseInput(){filterInputValue=filterInput.value.toLowerCase();filterInputValue=filterInputValue.replace(/ +(?= )/g,"");filterInputValue=filterInputValue.replace(" :",":");filterInputValue=filterInputValue.replace(": ",":");arguments=[];for(var a=!1,b=0,c=0;c<filterInputValue.length;c++)'"'==filterInputValue[c]&&(a=!a),a||" "!=filterInputValue[c]||(arguments.push(filterInputValue.substr(b,c-b)),b=c+1);arguments.push(filterInputValue.substr(b));inputMap=new Map;a=[];b="Name Title Description Parameter Parameter_description Since Autocorrect_parameter Autocorrect_parameter_description".split(" ");
for(c=0;c<b.length;c++)inputMap[b[c]]=[],inputMap[b[c]+" not Matched"]=[];var d=["ID","Severity","Parameter_name","Autocorrect_parameter_name"];for(c=0;c<d.length;c++)inputMap[d[c]]=[],inputMap[d[c]+" not Matched"]=[];b=new Set(b);d=new Set(d);var e=new Set;for(c=0;c<arguments.length;c++){var f=arguments[c].split(":");if(1==f.length)a.push(f[0]),e.add("free word");else if(f[1]=f[1].trim(),'"'==f[1][0]&&'"'==f[1][f[1].length-1]?f[1]=f[1].substr(1,f[1].length-2):"-"==f[1][0]&&'"'==f[1][1]&&'"'==f[1][f[1].length-
1]&&(f[1]="-"+f[1].substr(2,f[1].length-3)),f[0]="id"==f[0]?"ID":capitalizeFirstLetter(f[0]),f[1]=f[1].trim(),b.has(f[0])){if("-"==f[1][0]){f[1]=f[1].substr(1);var g=f[0]+" not Matched"}else g=f[0],e.add(g);g in inputMap||(inputMap[g]=[]);inputMap[g].push(f[1])}else if(d.has(f[0]))for(var p=f[1].split(","),l=0;l<p.length;l++){var h=p[l].trim();"-"==h[0]?(h=h.substr(1),g=f[0]+" not Matched"):(g=f[0],e.add(g));g in inputMap||(inputMap[g]=[]);inputMap[g].push(h)}}inputMap.FreeWords=a;inputMap["Different arguments"]=
e.size}function capitalizeFirstLetter(a){return a.charAt(0).toUpperCase()+a.slice(1)}
function filterSearch(){void 0==inputMap&&parseInput();var a=inputMap.FreeWords,b=inputMap["Different arguments"],c=new Set,d=new Set,e=new Set,f=new Set,g=new Set,p=new Set,l,h=allRulesInDefaultCategories;state==C.STATE.EDIT_RULESET&&(h=new Set,categoriesToRulesInRuleset.forEach(function(k,m){k.forEach(function(n){h.add(n)})}));nOfChecksMatched=nOfChecks=0;h.forEach(function(k){c.clear();d.clear();var m=k.querySelector("table").getElementsByTagName("tr"),n=!1;k.style.display="none";var u=k.closest(".category");
e.has(u)||(u.style.display="none");var B=u.id;l=k.id;var x=document.querySelector("li[data-id='"+l+"']");p.add(x);x=document.querySelector("li[data-id='"+B+"']");p.add(x);if(state==C.STATE.SELECT_RULES&&shouldHideAddedRules&&rulesWithCopiesInRuleset.has(k))unhighlightRule(m,!1);else{for(x=0;x<m.length;x++){var y=m[x].getElementsByTagName("th")[0],t=m[x].getElementsByTagName("td")[0];if(y&&t){var r=y.textContent||y.innerText;if("Parameters Values"!=r&&"Autocorrect Parameters Values"!=r&&"Autocorrect"!=
r&&(state!==C.STATE.EDIT_RULESET||"Description"!=r&&"Severity"!=r)&&(t.innerHTML=unhighlight(t),""!=filterInputValue)){y=t.innerText||t.textContent;if("Parameters"==r||"Parameters Description"==r)r="Parameter";if("Autocorrect Parameters"==r||"Autocorrect Parameters Description"==r)r="Autocorrect_parameter";"Date"==r&&(r="Since");var q=applyFilter(r,y,d,t);n=q[0];d=q[1];t.innerHTML=q[2];if(n)break;if("Parameter"==r){var w=y.split(" : ");var v=0;for(q=w[v];;){var z=w[v+1],A=z.lastIndexOf("."),D=z.substr(0,
A+1);q=applyFilter("Parameter_name",q,d,t);n=q[0];d=q[1];t.innerHTML=q[2];if(n)break;q=applyFilter("Parameter_description",D,d,t);n=q[0];d=q[1];t.innerHTML=q[2];if(n)break;q=z.substr(A+1);v++;if(""==q)break}}if("Autocorrect_parameter"==r)for(w=y.split(" : "),v=0,q=w[v];;){z=w[v+1];A=z.lastIndexOf(".");r=z.substr(0,A+1);q=applyFilter("Autocorrect_parameter_name",q,d,t);n=q[0];d=q[1];t.innerHTML=q[2];if(n)break;q=applyFilter("Autocorrect_parameter_description",r,d,t);n=q[0];d=q[1];t.innerHTML=q[2];
if(n)break;q=z.substr(A+1);v++;if(""==q)break}for(v=0;v<a.length;v++)w=a[v],-1<y.toLowerCase().indexOf(w)&&(c.add(w),""!=w&&(t.innerHTML=highlight(w,t)));0<a.length&&c.size==a.length&&d.add("free word")}}}if(""==filterInputValue||d.size==b&&!n)u.style.display="",k.style.display="",e.add(u),g.add(l),f.add(B);nOfChecks++}});nOfChecksMatched=g.size;filterResults.textContent=""==filterInputValue?nOfChecks+" checks":nOfChecksMatched+"/"+nOfChecks+" checks matched";state===C.STATE.SELECT_RULES&&null===
nOfAllChecks&&(nOfAllChecks=nOfChecks);hideToc(p,f,g);scroll(0,0)}function unhighlightRule(a,b){for(var c=0;c<a.length;c++){var d=a[c].getElementsByTagName("th")[0],e=a[c].getElementsByTagName("td")[0];if(b){var f=d.textContent||d.innerText;if("Parameters Values"==f||"Autocorrect Parameters Values"==f||"Description"==f||"Severity"==f)continue}d&&e&&(e.innerHTML=unhighlight(e))}}
function applyFilter(a,b,c,d){for(var e=inputMap[a],f=inputMap[a+" not Matched"],g,p=0;p<e.length;p++)g=e[p],filterCheck(a,b,e)&&(c.add(a),d.innerHTML=highlight(g,d));for(p=0;p<f.length;p++)if(filterCheck(a,b,f))return[!0,c,d.innerHTML];return[!1,c,d.innerHTML]}function filterCheck(a,b,c){return"Since"==a?new Date(b)>=new Date(c):-1<b.toLowerCase().indexOf(c)}
function hideToc(a,b,c){a.forEach(function(d){d.style.display="none";var e=d.dataset.id;b.has(e)?d.style.display="":c.has(e)&&(d.style.display="")})}function highlight(a,b){b=b.innerHTML;return b=b.replace(new RegExp("("+a+")(?!(.(?!<span))*</span>)","gi"),function(c){return"<span class='highlight'>"+c+"</span>"})}function unhighlight(a){a=a.innerHTML;return a=a.replace(/<\/?span[^>]*>/g,"")}
function toggleHelp(){var a=document.getElementById("helpDiv");a.style.display="none"==a.style.display?"":"none"}function showHelp(){document.getElementById("helpDiv").style.display=""}function hideHelp(a){var b=document.getElementById("helpDiv");a.target.matches(".wrap *")||(b.style.display="none")};
